# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js image as a parent image
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the TypeScript source code
COPY src ./src
COPY tsconfig.json ./

# Build the TypeScript code
RUN npm run build

# Use a lightweight image for the final build
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy the build files from the builder stage
COPY --from=builder /app/build ./build
COPY package.json ./

# Install only production dependencies
RUN npm ci --omit=dev

# Expose the port on which the server will run (if required)
# EXPOSE 8080

# Define environment variables
ENV GOOGLE_API_KEY=your-api-key-here
ENV GOOGLE_SEARCH_ENGINE_ID=your-search-engine-id-here

# Run the application
ENTRYPOINT ["node", "build/index.js"]
